
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/miniconda3/envs/coupled/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.5.0 - arm64
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/private/var/folders/w9/1m4r7w0n2sd_91m1gr6yykqc0000gn/T/pip-build-env-07ybbcpi/overlay/lib/python3.11/site-packages/cmake/data/share/cmake-4.2/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.5.0 - arm64
...
